### ISSUE TITLE
Addon conflicts with Minimap Button Bag (MBB) addon

### ISSUE THREAD

**Issue by Maczuga** [Wuild/GatherLite#74]
**Describe the bug**
When GatherLite is enabled together with MBB - every movement try generates a 2sec lag. Also it floods the MBB with vein/herb icons (see screenshot).

**To Reproduce**
1. Install MBB addon from here: https://www.curseforge.com/wow/addons/mbb
2. Launch the game with GatherLite and MBB enabled
3. Game lags whenever a character moves and MBB is filled with GatherLite icons

**Expected behavior**
Icons should remain on minimap and should not be causing the lag when combined with MBB.

**Screenshots**
![image](https://user-images.githubusercontent.com/544349/64973389-39120400-d8ab-11e9-8f36-47f6f8a6deeb.png)

**Additional context**
There was a similar problem with Questie addon, however it's fixed in it's 4.1.0 version, might be worth checking. Looks like that's the commit: https://github.com/AeroScripts/QuestieDev/commit/b5743424842d8ce47c33c2ea0bdbdbf9d5c43d58
Disabling GatherLite prevents the icon spam and lag.

**Comment by Wuild** [comment]
this has been fixed

**Comment by Maczuga** [comment]
Still occurrs, but only in special condition:

1. Toggle addon off by Shift-click the mini-map icon.
2. /reload
3. Toggle addon on - no icons in MBB (works fine here).
4. /reload
5. Addon is on, icons are back in MBB, lag is here too.

**Comment by Maczuga** [comment]
@Wuild I don't know if you have seen this. This issue needs to be reopened. Also with the recent version - lag still occurrs when using with MBB.

**Comment by Wuild** [comment]
I was missing the MBB dep. please try version 1.3.0 as it is working for me.

**Comment by Maczuga** [comment]
@Wuild 
I am using 1.3.0, 

Those are my settings:
![image](https://user-images.githubusercontent.com/544349/65140041-f87ecb80-da0d-11e9-9d9a-0531ffd19536.png)

If I enable the GatherLite via Shift-clicking the minimap icon and /reload - lag is back. Also you can see there is 1 Mithril Ore icon in my MBB.

Also with last 2 options checked I still get lots of ore icons in MBB + even bigger when I try to move my character (see below).

![image](https://user-images.githubusercontent.com/544349/65140256-717e2300-da0e-11e9-9fe3-36bcdd10b8b3.png)

**Comment by Wuild** [comment]
hmm wierd... ill have a look at it

**Comment by Wuild** [comment]
ah! it's been fixed, ill publish a new release soon
